### ISSUE TITLE
fitlinxx documentation

### ISSUE THREAD

**Issue by edschminke** [mdeltito/node-csafe#3]
Since fitlinxx seems to have gone away, so has the CSAFE protocol specification document.  Did you have a copy of that and do you still? If so, could you commit it to this repo?  Much appreciated!

**Comment by mdeltito** [comment]
There were two documents, if I remember correctly. [This mirror](http://read.pudn.com/downloads198/sourcecode/middleware/933991/CSAFE_Framework.pdf) is at least part of the spec, but there's a more complete reference of the various command sequences that I can't find online at the moment. If I can find the files on my old machine I'll preserve them somewhere!

**Comment by edschminke** [comment]
That would be great if you could find it.  The link you posted, was that a portion of the whole that you worked from? Did you implement the entire protocol such that your code could be used as a roadmap to implement in other languages?

**Comment by KyleGW** [comment]
Found it in the wayback machine here:
https://web.archive.org/web/20071206133033/http://www.fitlinxx.com:80/CSAFE/specification.htm

**Comment by edschminke** [comment]
You rock KyleGW!

**Comment by mdeltito** [comment]
thanks @KyleGW !
